layout_spectrum: 0.9844254
color:
  saturation: 0.8694951
  brandStrength: 0
  lightness: 0.6836735
  brandColors:
    - '#AAAAAA'
    - '#8F8F91'
    - '#896C4A'
    - '#E9E9E1'
    - '#4B4430'
  rhythmicContrast: 0.7577873
typography_spectrum: 0.7180451
name: DryFlyGirl
