name: DryFlyGirl
favicon: null
layout_spectrum: 0.09092
typography_spectrum: 0.54316
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#749379'
    - '#040301'
    - '#7e7539'
    - '#e7d18f'
    - '#4b441c'
  brandStrength: 0.5
  lightness: 0.6836735
  saturation: 0.8694951
  rhythmicContrast: 0.7577873
purpose: []
